<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="WolverineFx" Version="6.21.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.21.0" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Profile.Domain\Profile.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\shared\E-Commerce.Server.Shared.Localization\E-Commerce.Server.Shared.Localization\E-Commerce.Server.Shared.Localization.csproj" />
  </ItemGroup>
</Project>
