<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>E_Commerce.Server.Shared.Logging</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql" Version="10.0.3" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Sinks.Postgresql.Alternative" Version="4.2.0" />
		<PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="9.0.1" />
	</ItemGroup>
	
</Project>
