<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>E_Commerce.Server.Shared.Authentication</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\E-Commerce.Server.Shared.Caching\E-Commerce.Server.Shared.Caching\E-Commerce.Server.Shared.Caching.csproj" />
  </ItemGroup>

</Project>
